force-app/main/default/objects/Contract/fields/CloudService__c.field-meta.xml
<CustomField>
    <fullName>CloudService__c</fullName>
    <label>クラウドサービス</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CloudService</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/ContractId__c.field-meta.xml
<CustomField>
    <fullName>ContractId__c</fullName>
    <label>契約ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/piDeletedUserEnv__c.field-meta.xml
<CustomField>
    <fullName>piDeletedUserEnv__c</fullName>
    <defaultValue>false</defaultValue>
    <label>クラウドサービス環境削除</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/recordTypes/CloudService.recordType-meta.xml
<RecordType>
    <fullName>CloudService</fullName>
    <active>true</active>
    <label>クラウドサービス</label>
</RecordType>

force-app/main/default/globalValueSets/CloudService.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PochittoInvoice</fullName>
        <label>ポチッと請求</label>
    </customValue>
    <masterLabel>クラウドサービス</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/pdPIContractBatch.cls
public class pdPIContractBatch implements Database.Batchable<sObject>, Database.AllowsCallouts {
    /**
     * 以下の条件に合致する契約を返す
     * * 契約レコードタイプがクラウドサービス
     * * 契約のクラウドサービスがポチッと請求
     * * クラウドサービス契約IDがnull以外
     * * クラウドサービス環境削除フラグがfalse
     * * 契約終了日から32日が経過
     */
    public Database.QueryLocator start(Database.BatchableContext bc) {
        ID recordTypeId = [SELECT Id FROM RecordType WHERE SobjectType='Contract' AND DeveloperName='CloudService'].Id;

        Date startDate = Date.today();
        startDate = startDate.addDays(-32);

        return Database.getQueryLocator(
            [
                SELECT Id,ContractId__c,piDeletedUserEnv__c
                FROM Contract
                WHERE RecordTypeId = :recordTypeId
                    AND CloudService__c = 'PochittoInvoice'
                    AND ContractId__c != null
                    AND EndDate < :startDate
                    AND piDeletedUserEnv__c = false
            ]
        );
    }

    /**
     * 契約の環境を削除する
     * 環境を削除したら、ポチッと請求環境削除フラグを設定する
     */
    public void execute(Database.BatchableContext bc, List<Contract> lstContract) {
        for (Contract contract: lstContract) {
            pdPIAuth0.deleteUser(contract.ContractId__c);
            pdPIAzure.deleteUserEnv(contract.ContractId__c);

            contract.piDeletedUserEnv__c = true;
        }

        update lstContract;
    }

    /**
     * 終了処理を行う
     */
    public void finish(Database.BatchableContext bc) {
    }
}