force-app/main/default/objects/Contract/fields/ContractId__c.field-meta.xml
<CustomField>
    <fullName>ContractId__c</fullName>
    <label>契約ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/piDeletedUserEnv__c.field-meta.xml
<CustomField>
    <fullName>piDeletedUserEnv__c</fullName>
    <defaultValue>false</defaultValue>
    <label>クラウドサービス環境削除</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/pdPochittoInvoiceContractBatch_test.cls
@isTest
class pdPochittoInvoiceContractBatch_test {
    @TestSetup
    static void setup(){
        Account account = new Account(
            Name = 'ぴたデジ株式会社'
        );
        insert account;

        Contract contract = new Contract(
            Name = '契約',
            AccountId = account.Id,
            StartDate = Date.today().addDays(-60),
            Status = 'Draft',
            ContractId__c = 'test',
            piDeletedUserEnv__c = false
        );
        insert contract;
        contract.Status = 'End';
        contract.EndDate = Date.today().addDays(-33);
        update contract;

    }

    @isTest
    static void test_pdPochittoInvoiceContractBatch() {
        Test.setMock(HttpCalloutMock.class, new pdPochittoInvoice_mock());

        Test.startTest();

        pdPochittoInvoiceContractBatch b = new pdPochittoInvoiceContractBatch();
        Database.executeBatch(b);

        Test.stopTest();
    }
}