force-app/main/default/objects/Account/fields/AccountCode__c.field-meta.xml
<CustomField>
    <fullName>AccountCode__c</fullName>
    <label>取引先コード</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FullName__c.field-meta.xml
<CustomField>
    <fullName>FullName__c</fullName>
    <label>正式名称</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>請求</label>
    <nameField>
        <label>請求名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/InvoiceDate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceDate__c</fullName>
    <label>請求日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/IssueCount__c.field-meta.xml
<CustomField>
    <fullName>IssueCount__c</fullName>
    <label>発行数</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/IssueUnitPrice__c.field-meta.xml
<CustomField>
    <fullName>IssueUnitPrice__c</fullName>
    <label>発行単価</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/PageUnitPrice__c.field-meta.xml
<CustomField>
    <fullName>PageUnitPrice__c</fullName>
    <label>ページ単価</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/pdPIFreee_test.cls
@isTest
class pdPIFreee_test {
    @isTest
    static void test_registInvoice() {
        Date startDate = Date.newInstance(2021, 5, 1);
        Date endDate = Date.newInstance(2021, 5, 31);
        Account account = new Account(
            Name = 'Test',
            FullName__c = 'Test',
            AccountCode__c = 'test',
            Phone = '000-0000-0000',
            BillingPostalCode = '020-0611',
            BillingState = '岩手県',
            BillingCity = '滝沢市',
            BillingStreet = '巣子１５２番地４０９滝沢市第２イノベーションセンター'
        );
        Contact contact = new Contact(
            FirstName = 'test',
            LastName = 'test',
            Department = 'test',
            Email = 'test@test.jp'
        );
        Invoice__c invoice = new Invoice__c(
            Name = 'test',
            IssueCount__c = 100,
            IssueUnitPrice__c = 35,
            PageCount__c = 200,
            PageUnitPrice__c = 15,
            InvoiceDate__c = Date.newInstance(2021, 5, 31)
        );

        Test.setMock(HttpCalloutMock.class, new pdPIHttpCallout_mock());

        Test.startTest();

        pdPIFreee piFreee = new pdPIFreee();
        piFreee.registInvoice(startDate, endDate, account, contact, invoice);

        Test.stopTest();
    }
}