force-app/main/default/objects/PricebookEntry/fields/InitUnitPrice__c.field-meta.xml
<CustomField>
    <fullName>InitUnitPrice__c</fullName>
    <label>初期リスト価格</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ServiceApplication__c/ServiceApplication__c.object-meta.xml
<CustomObject>
    <label>サービス申込</label>
    <nameField>
        <displayFormat>SA{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>サービス申込コード</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceApplication__c/fields/Bill__c.field-meta.xml
<CustomField>
    <fullName>Bill__c</fullName>
    <label>ビル名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceApplication__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>市区郡</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceApplication__c/fields/CompanyName__c.field-meta.xml
<CustomField>
    <fullName>CompanyName__c</fullName>
    <label>会社名</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceApplication__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>部署名</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceApplication__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>名</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceApplication__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>姓</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceApplication__c/fields/MailAddress__c.field-meta.xml
<CustomField>
    <fullName>MailAddress__c</fullName>
    <label>メールアドレス</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/ServiceApplication__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>電話番号</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/ServiceApplication__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>郵便番号</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceApplication__c/fields/ServiceName__c.field-meta.xml
<CustomField>
    <fullName>ServiceName__c</fullName>
    <label>サービス名</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CloudService</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceApplication__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>都道府県</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceApplication__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>町名・番地</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/CloudService.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PochittoInvoice</fullName>
        <label>ポチッと請求</label>
    </customValue>
    <masterLabel>クラウドサービス</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/pdPIRegistration_test.cls
@isTest
class pdPIRegistration_test {
    @TestSetup
    static void setup(){
        Pricebook2 pricebook2 = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
        );
        update pricebook2;

        Product2 product2 = new Product2(
            Name = 'ポチッと請求',
            ProductCode = 'PI0001'
        );
        insert product2;

        PricebookEntry pricebookEntry = new PricebookEntry(
            Pricebook2Id = pricebook2.Id,
            Product2Id = product2.Id,
            UnitPrice = 0,
            IsActive = true,
            InitUnitPrice__c = 50000
        );
        insert pricebookEntry;

        ServiceApplication__c serviceApplication = new ServiceApplication__c();
        serviceApplication.ServiceName__c = 'ポチッと請求';
        serviceApplication.CompanyName__c = '**テスト株式会社';
        serviceApplication.PostalCode__c = '020-0611';
        serviceApplication.State__c = '岩手県';
        serviceApplication.City__c = '滝沢市';
        serviceApplication.Street__c = '巣子152-409';
        serviceApplication.Bill__c = '滝沢市第2イノベーションセンター';
        serviceApplication.Department__c = '経理部';
        serviceApplication.LastName__c = '俣江';
        serviceApplication.FirstName__c = '幸治';
        serviceApplication.Phone__c = '019-618-0161';
        serviceApplication.MailAddress__c = 'test@test.jp';
        insert serviceApplication;
    }

    @isTest
    static void test_regist() {
        List<ServiceApplication__c> lstServiceApplication = [SELECT Id, ServiceName__c, CompanyName__c, PostalCode__c, State__c, City__c,
                                                            Street__c, Bill__c, Department__c, LastName__c, FirstName__c, Phone__c, MailAddress__c
                                                            FROM ServiceApplication__c];

        Test.setMock(HttpCalloutMock.class, new pdPIHttpCallout_mock());

        Test.startTest();
        pdPIRegistration.regist(lstServiceApplication);
        Test.stopTest();

        List<Account> lstAccount = [SELECT Id,Name FROM Account];
        System.assertEquals(lstAccount.size(), 1, '取引先が作成されていません');

        List<Contact> lstContact = [SELECT Id,Name FROM Contact];
        System.assertEquals(lstContact.size(), 1, '取引先責任者が作成されていません');

        List<Contract> lstContract = [SELECT Id,Name FROM Contract];
        System.assertEquals(lstContract.size(), 1, '契約が作成されていません');

        List<Order> lstOrder = [SELECT Id,Name FROM Order];
        System.assertEquals(lstOrder.size(), 1, '注文が作成されていません');

        List<OrderItem> lstOrderItem = [SELECT Id FROM OrderItem];
        System.assertEquals(lstOrderItem.size(), 1, '注文商品が作成されていません');
    }

    class TestParam {
        public String customer;
    }
}