force-app/main/default/objects/PostalRequest__c/PostalRequest__c.object-meta.xml
<CustomObject>
    <label>郵送依頼</label>
    <nameField>
        <displayFormat>PR-{YYYY}{MM}{DD}-{000}</displayFormat>
        <label>郵送依頼ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PostalRequest__c/fields/PostalRequestCount__c.field-meta.xml
<CustomField>
    <fullName>PostalRequestCount__c</fullName>
    <label>郵送依頼数</label>
    <summarizedField>PostalRequestDetail__c.PostalRequestCount__c</summarizedField>
    <summaryForeignKey>PostalRequestDetail__c.PostalRequest__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/PostalRequest__c/fields/PostalRequestDate__c.field-meta.xml
<CustomField>
    <fullName>PostalRequestDate__c</fullName>
    <label>郵送依頼日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PostalRequestDetail__c/PostalRequestDetail__c.object-meta.xml
<CustomObject>
    <label>郵送依頼明細</label>
    <nameField>
        <label>契約ID</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PostalRequestDetail__c/fields/PostalRequest__c.field-meta.xml
<CustomField>
    <fullName>PostalRequest__c</fullName>
    <label>郵送依頼</label>
    <referenceTo>PostalRequest__c</referenceTo>
    <relationshipLabel>郵送依頼明細</relationshipLabel>
    <relationshipName>PostalRequestDetails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PostalRequestDetail__c/fields/PostalRequestCount__c.field-meta.xml
<CustomField>
    <fullName>PostalRequestCount__c</fullName>
    <label>郵送依頼数</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/pdPIPostalRequest_test.cls
@isTest
class pdPIPostalRequest_test {
    @isTest
    static void aggregatePostal_test() {
        Test.setMock(HttpCalloutMock.class, new pdPIHttpCallout_mock());

        Test.startTest();
    
        pdPIPostalRequest.aggregatePostal();

        String yesterday = String.valueOf(Date.today().addDays(-1));
        /*
        List<PostalRequest__c> lstp = [SELECT Id FROM PostalRequest__c WHERE NAME=:yesterday];
        System.assertEquals(1, lstp.size(), '郵送依頼データが１件ではありません。');

        List<PostalRequestDetail__c> lstd = [SELECT Id FROM PostalRequestDetail__c WHERE PostalRequest__c=:lstp[0].Id];
        System.assertEquals(2, lstd.size(), '郵送依頼明細データが１件ではありません。');
        */
        Test.stopTest();
    }

    @isTest
    static void getPiPostal_test() {
        PostalRequest__c postalRequest = new PostalRequest__c(
            PostalRequestDate__c = Date.today()
        );
        insert postalRequest;
        PostalRequestDetail__c postalRequestDetail = new PostalRequestDetail__c(
            PostalRequest__c = postalRequest.Id,
            Name = 'test',
            PostalRequestCount__c = 10
        );
        insert postalRequestDetail;

        Test.startTest();

        List<PostalRequest__c> lstPostalRequest = pdPIPostalRequest.getPostalRequest();

        System.assertEquals(lstPostalRequest.size(), 1, '取得した郵送依頼が１件ではありません');

        Test.stopTest();
    }
}